# Generated by Django 3.2.6 on 2021-09-03 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friendList',
            field=models.ManyToManyField(blank=True, related_name='_api_customuser_friendList_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(upload_to='', verbose_name='images/'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='this', to=settings.AUTH_USER_MODEL)),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='that', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
