# Generated by Django 3.2.6 on 2021-09-05 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_groups_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.groups'),
        ),
    ]
