# Generated by Django 3.2.6 on 2021-09-18 06:25

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210905_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='friendList',
            field=models.ManyToManyField(blank=True, null=True, related_name='_api_customuser_friendList_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to=api.models.getname),
        ),
    ]
